name: formgaurd
description: "FormGuard is a Dart package designed specifically for Flutter applications. It provides validators for handling form validation tasks in a Flutter-friendly manner. Since Flutter apps are built using Dart, the package can seamlessly integrate into any Flutter project to simplify and streamline form validation."
version: 0.0.1
license: MIT
homepage: https://github.com/Atanu-Sabyasachi/formgaurd/tree/main
repository: https://github.com/Atanu-Sabyasachi/formgaurd/tree/main

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: