name: formgaurd
description: "A new Flutter package project."
version: 0.0.1
license: MIT
homepage: https://github.com/Atanu-Sabyasachi/formgaurd/tree/main
repository: https://github.com/Atanu-Sabyasachi/formgaurd/tree/main

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: